Features/django
Gandi/python-zipkin pull request #5
Opened 2021-06-17 06:47 UTC by mardiros

start implementation for django.

Note that ee cannot attach event to sql on the ORM of django.

2021-06-17 08:11 UTC, Themimitoof commented
@mardiros don't forget to update the `setup.py` to add `django` in the `extra_requires`

2021-06-17 08:11 UTC, Themimitoof requested changes

2021-06-17 08:11 UTC, Themimitoof commented on zipkin/binding/psycopg2/tracer.py
> +import logging
Import non used.

```suggestion
```

2021-06-17 15:28 UTC, mardiros commented on zipkin/binding/psycopg2/__init__.py
> +from .tracer import TraceCursor, TraceConnection
Run Isort too

2021-06-17 15:29 UTC, mardiros commented on zipkin/binding/psycopg2/tracer.py
> +import logging
DONE

2021-06-17 15:35 UTC, Themimitoof approved these changes
LGTM :+1:

2021-06-18 06:52 UTC, gdchamal approved these changes
Just a remark about a class variable

2021-06-18 06:59 UTC, mardiros commented on zipkin/binding/psycopg2/tracer.py
> +    count = 1
Debugging purpose, to remove.

2021-06-18 08:58 UTC, Themimitoof commented on zipkin/binding/psycopg2/tracer.py
> +    count = 1
Removed here: https://github.com/Gandi/python-zipkin/pull/6/files#diff-f0972ebb6e5ccf70d0677505fb969971194c1f50e4ba427580953f62c97e0c87L60

2021-06-22 06:44 UTC, merged